### ISSUE TITLE
Problem z działaniem pluginu

### ISSUE THREAD

**Issue by Maciek2136** [Craftserve/CraftserveRadiation#2]
Pobrałem plugin właczyłem serwer (z WorldGuardem). Plugin nie tworzy granicy, a gdzy wpisuje /pl pokazuje plugin jako aktywny
logi: https://pastebin.com/z23TZjKx

**Comment by TheMolkaPL** [comment]
Czy stworzyłeś region w WorldGuard definiujący obszar wolny od radiacji.

**Comment by Maciek2136** [comment]
a jak to zrobic?

**Comment by TheMolkaPL** [comment]
Potrzebujesz do tego różdżki WorldEdit, domyślnie jest to drewniana siekiera. Możesz ją sobie dać komendą `//wand`. Następnie używając tej różdżki musisz sobie zrobić zaznaczenie. Klikając LPM różdżką zaznaczasz pierwszy punkt, klikając PPM zaznaczasz drugi punkt. Gdy zaznaczysz oba punkty, a mają to być skrajne punkty, najdalej od siebie oddalone możesz powiększyć zaznaczenie, aby objęło całą wysokość świata - robisz to komendą `//expand vert`. W innym przypadku zaznaczenie będzie obejmowało wyłącznie obszar na wysokości którą zaznaczyłeś (czyli między oboma punktami).

Teraz posiadając zaznaczenie możesz sobie stworzyć region. Domyślna nazwa regionu to `km_safe_from_radiation`. Jeżeli ta nazwa nie została zmieniona w konfiguracji pluginu wpisujesz `/rg create km_safe_from_radiation`. Tak oto stworzyłeś region. Teraz musisz zdjąć z niego ochronę, ponieważ tylko OP może na nim budować i niszczyć. Robisz to komendą `/rg flag km_safe_from_radiation passthrough allow`.

Teraz po wyjściu z tego regionu powinien pokazywać się boss bar oraz gracze powinni otrzymywać obrażenia.

**Comment by Maciek2136** [comment]
dzięki za pomoc powinieneś dodać to do opisu pluginu chyba że to juz jest bo nie widzialem
