### ISSUE TITLE
Nie działająca komenda /rg flag __global__ radiation yes i /rg flag km_safe_from_radiation radiation yes

### ISSUE THREAD

**Issue by Skw972** [Craftserve/CraftserveRadiation#23]
Nie wykrywa mi takiej flagi jak radiation, czy wie ktoś jak to naprawić?

**Comment by TheMolkaPL** [comment]
Funkcja flag nie została jeszcze wydana w oficjalnej wersji. Skorzystaj z tych instrukcji: https://github.com/Craftserve/CraftserveRadiation/tree/v1.1.2
