### ISSUE TITLE
Strefa radiacji nie bije

### ISSUE THREAD

**Issue by MonsieurCookie** [Craftserve/CraftserveRadiation#24]
Strefa dodaje efekt wither, aczkolwiek nie zadaje on obrażeń(jak się wchodzi dostaje się 1 strzał i następnie nic, można dowolnie eksplorować strefę radiacji)
Pluginy: AuthMe, CoreProtect, Essentials, FAWE, LuckPerms, MaxBansPlus, NametagEdit, SuperVanish, VoxelSniper, WorldGuard, Vault
Inaczej pozyskany efekt wither (przez witherowego szkieleta, withera lub komendą) działa bez zarzutu, próbowałem różnych wartości w configu.

**Comment by TheMolkaPL** [comment]
To nie jest związane z radiacją. Masz po prostu goda. Może to być spowodowane flagą nieśmiertelności w WorldGuard (invincible), albo SuperVanish (masz vanisha?), albo Essentials (`/god`) albo AuthMe.
