### ISSUE TITLE
Bukkit 1.16

### ISSUE THREAD

**Issue by Gunvcio** [Craftserve/CraftserveRadiation#28]
When version 1.16.1?
Kiedy wersja   1.16.1?

**Comment by Cubixmeister** [comment]
Kiedy będziemy mieli potrzebę to zaktualizujemy.
Chętnie przyjmiemy PR z odpowiednimi zmianami ;)

**Comment by Gunvcio** [comment]
Dzięki za odpowiedź.A jest sposób aby wersja tego pluginu z 1.15 zadziałała na spigocie 1.16.1. bo próbuje i nie działa.

**Comment by TheMolkaPL** [comment]
https://github.com/Craftserve/CraftserveRadiation/commit/007ede1ff6ff94eeab8b77754cd130ed59bc6487
