### ISSUE TITLE
Strefa Radiacji - Pomoc 

### ISSUE THREAD

**Issue by MrAdrianek** [Craftserve/CraftserveRadiation#32]
Witam,
Mam takie pytanie czy da się zrobić na wersji 1.16.1 tak, by radiacja była tylko w całym nether?

**Comment by TheMolkaPL** [comment]
Wystarczy włączyć radiację w regionie `__global__`, `__global__` istnieje zawsze w każdym świecie.

```
/rg flag __global__ radiation true
```

**Comment by MrAdrianek** [comment]
Czyli nie da się zrobić tak, by było tylko w netherze?

**Comment by TheMolkaPL** [comment]
Napisałem komendę, jak zrobić globalnie w netherze... Jak nie chcesz w głównym świecie to po prostu nie ustawiasz tam radiacji.

**Comment by MrAdrianek** [comment]
Dziękuje

**Comment by MrAdrianek** [comment]
PS: Da się zmienić kolor tej reklamy craftserve?

**Comment by TheMolkaPL** [comment]
Niestety, reklama jest zapisana na twardo w kodzie źródłowym. Wysyłana jest do osób posiadających uprawnienie `craftserveradiation.ad`, domyślnie posiadają go tylko operatorzy serwera. Jeżeli nie chcesz jej wyświetlać wystarczy zabrać uprawnienie.

**Comment by MrAdrianek** [comment]
Dziękuje za pomoc, Mega plugin. Pozdrawiam

**Comment by ryaNNNq** [comment]
Witam, mam problem, ponieważ plugin nie jest wykrywany. Jest wgrany, a w grze po wpisaniu komendy /pl nawet sie nie wyswietla. Chodzi mi tu o najnowsza wersje.
