### ISSUE TITLE
Dostępność pluginu na wersję 1.16.4

### ISSUE THREAD

**Issue by Wiktorzynka** [Craftserve/CraftserveRadiation#38]
Witam,
wiadomo kiedy wyjdzie wersja pluginu na 1.16.4? Obecny plugin pokazuje w logach, że moja wersja jest niekompatybilna (paper-288 wersja 1.16.4), mimo posiadania najnowszego wydania (CraftserveRadiation-1.2-pre4) ze wsparciem 1.16 (mam wgrany WorldGuard).

**Comment by TheMolkaPL** [comment]
Dodane w #39, przetestuje to i zrobię release.

**Comment by TheMolkaPL** [comment]
https://github.com/Craftserve/CraftserveRadiation/releases/tag/v1.2
