### ISSUE TITLE
new cmd

### ISSUE THREAD

**Issue by dinobossytnew** [Craftserve/CraftserveRadiation#43]
/csr set area radiation
add a command for radiation zone  

add a custom armor support haxecode and model 3d.

**Comment by TheMolkaPL** [comment]
> /csr set area radiation
add a command for radiation zone

There is `/rg flag <region> radiation true`

**Comment by Cubixmeister** [comment]
Nadmiarowe wg mnie, jest flaga wordguard jak wyżej - zamykam
