### ISSUE TITLE
Plugin jest niekompatybilny z wersją 1.17

### ISSUE THREAD

**Issue by Meskotur** [Craftserve/CraftserveRadiation#44]
Tak jak w tytule. Plugin nie działa z wersją 1.17

**Comment by KaVVaski** [comment]
to prawda, nie działa - a bardzo by się przydał.

**Comment by TheMolkaPL** [comment]
Przy dodaniu wsparcia 1.17 należy pamiętać o [`getMinHeight()` i `getMaxHeight()`]( https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/World.java#1508-1524).

**Comment by mrozo94** [comment]
Nie mam praktycznie żadnego doświadczenia z pluginami, więc wybaczcie jeśli moje uwagi nic nie wnoszą.

Próbowałem zrobić wsparcie dla 1.17, ale wydaje mi się że jednym z problemów do rozwiązania są zmiany z NMSach które wprowadził spigot (szczegóły tutaj -> https://www.spigotmc.org/threads/spigot-bungeecord-1-17-1-17-1.510208/)

Także poza samym dodaniem wersji, będzie trzeba zmienić mappingi w `V1_14ToV1_15NmsBridge.java`.

Ale powtarzam, moja znajomość pluginowania (nie mówiąc już o NMS) jest żadna.

**Comment by TheMolkaPL** [comment]
Spigot używa starych mappingów, Paper używa teraz mappingów Mojangu.

**Comment by TheMolkaPL** [comment]
Zapraszam do pobierania: https://github.com/Craftserve/CraftserveRadiation/releases/tag/v1.3
