### ISSUE TITLE
Craftserve radiation 1.18

### ISSUE THREAD

**Issue by xAdrianab** [Craftserve/CraftserveRadiation#46]
Witam, czy ktoś jest w stanie zaaktualizować plguin craftserve radiation do wersji 1.18?

**Comment by rainb0wek** [comment]
+1

**Comment by rainb0wek** [comment]
Nikt nie jest chętny ? ;cccc

**Comment by TheMolkaPL** [comment]
643d8ed33a2b2626222ca9acce1bc0bc371a93df

**Comment by TheMolkaPL** [comment]
Zapraszam do pobierania: https://github.com/Craftserve/CraftserveRadiation/releases/tag/v1.4
