### ISSUE TITLE
Minecraft 1.19

### ISSUE THREAD

**Issue by WodzuShadows** [Craftserve/CraftserveRadiation#49]
Hej mam pytanie odnoścnie czy będzie radiacjia dostępna na wersje 1.19?

**Comment by Roderofficial** [comment]
Podpinam się

**Comment by Cubixmeister** [comment]
Niestety nie mamy czasu się teraz tym zajmować, ale PR są mile widziane ;)

Karol Piłat

**Comment by TheMolkaPL** [comment]
005a2e0bd30f4c4011bd5aabd0a1ea1c9f125b34
