### ISSUE TITLE
Da się usunąć spam reklamą craftserve?

### ISSUE THREAD

**Issue by 7extension** [Craftserve/CraftserveRadiation#56]
Tak jak wyżej, nie chce, aby na chacie był spam jak bym hostował serwer na darmowym hostingu xD

**Comment by TheMolkaPL** [comment]
Informacja o Craftserve wysyłana jest tylko i wyłącznie przy dołączeniu graczy do serwera posiadającego uprawnienie `craftserveradiation.ad`. To uprawnienie nadane jest domyślnie wyłącznie operatorom serwera. Innymi słowami - wiadomość ta, domyślnie, wysyłana jest wyłącznie dla OP-ów. Możesz odebrać to uprawnienie na przykład pluginem od uprawnień [LuckPerms](https://luckperms.net/).
